/// Flutter icons Scanner
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Scanner
///      fonts:
///       - asset: fonts/Scanner.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Scanner {
  Scanner._();

  static const _kFontFam = 'Scanner';
  static const String? _kFontPkg = null;

  static const IconData scanner = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
